spring:
  application:
    name: demo
  profiles:
    include:
    - private

springdoc:
  swagger-ui:
    path: /ui.html
    
server:
  port: 8080
    
 
mybatis:
  configuration:
    jdbc-type-for-null: VARCHAR
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.mobilefactory.lotto.*.model.vo, com.mobilefactory.lotto.*.model.dto
  mapper-locations: classpath:mapper/**/*.xml


logging:
  level:
    root: info
    org.mybatis: debug
    org.apache.ibatis: debug     