spring:
  application:
    name: demo
  profiles:
    include:
    - private
  jackson:
    time-zone: Asia/Seoul
    date-format: yyyy-MM-dd HH:mm:ss

springdoc:
  swagger-ui:
    path: /ui.html
    
server:
  port: 8080

mybatis:
  configuration:
    jdbc-type-for-null: VARCHAR
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.mobilefactory.lotto.**
  mapper-locations: classpath:mapper/**/*.xml


logging:
  level:
    root: info
    org.mybatis: debug
    org.apache.ibatis: debug     